### ISSUE TITLE
Npm Start Error

### ISSUE THREAD

**Issue by leonardosouzafaria** [LFeh/1500-translator#10]
Instalei os pacotes tudo certinho mas quando dou o comando `npm start` aparece o seguinte erro:

D:\Souza\Workspace\1500-translator>npm start

> 1500-translator@1.0.0 start D:\Souza\Workspace\1500-translator
> NODE_ENV=development webpack-dev-server

```
'NODE_ENV' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 1500-translator@1.0.0 start: `NODE_ENV=development webpack-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 1500-translator@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Developer\AppData\Roaming\npm-cache\_logs\2018-04-10T11_50_55_029Z-debug.log
```

**Comment by LFeh** [comment]
O ideal nesse caso é modificar o package.json pra rodar no Windows (não commita), e adicionar `set NODE_ENV=` no lugar de `NODE_ENV=`...

Veja se funciona.

**Comment by leonardosouzafaria** [comment]
Funcionou !! 
Obrigado 👍
