### ISSUE TITLE
Relação de termos técnicos para fins exploratórios

### ISSUE THREAD

**Issue by g0d0** [LFeh/1500-translator#14]
Para os que entrarem no site e não souberem por qual termo pesquisar ou para explorar termos desconhecidos, talvez fosse interessante adicionar uma relação de termos técnicos [renderizados aleatoriamente].

**Comment by LFeh** [comment]
Já vir preenchido / traduzido?

**Comment by g0d0** [comment]
Fiquei com a mesma dúvida.
Se vier preenchido não tem porque o usuário utilizar o "componente de tradução", todavia, talvez fosse interessante utilizar o "componente de tradução" para recomendar ao usuário termos relacionados ao "termo traduzido".

**Comment by LFeh** [comment]
Dá pra vir preenchido sim, talvez como placeholder e o resultado ao lado. Gostei da ideia, vou criar uma issue em ingreis :)
