### ISSUE TITLE
Translating words with special charachters

### ISSUE THREAD

**Issue by luisfmsouza** [LFeh/1500-translator#28]
I think it's not translating words with special characters, take a look:

![image](https://user-images.githubusercontent.com/4405147/43597081-682bc2b8-9657-11e8-95b8-ec07f56acf9f.png)

## Update

If we remove the special characters from the given word, it translates:

![image](https://user-images.githubusercontent.com/4405147/43597162-a0ce60b2-9657-11e8-997f-519baa04ab44.png)

**Comment by LFeh** [comment]
Uhmmmm, we can add some variables of same word on json file...

**Comment by luisfmsouza** [comment]
Think thats because we [remove the accent here](https://github.com/LFeh/1500-translator/blob/master/src/js/convert.js#L3).

Maybe we can map the words to a version without accents [here](https://github.com/LFeh/1500-translator/blob/master/src/library.json), like:

```js
// from
"corrupção": "jeitinho brasileiro"

// to
"corrupcao": "jeitinho brasileiro"
```

**Comment by LFeh** [comment]
Ahhhh, good point, I'll remove the accents

**Comment by LFeh** [comment]
Think that major problem is because the `forEach` is replace the initial array and removing the initial words.

Maybe using immutable variables will to resolve it.
